# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Image',
            field=models.ImageField(upload_to='/home/deependra/serverPothole/media/images', verbose_name='Image'),
        ),
    ]
