# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20160504_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Severity',
            field=models.FloatField(blank=True, default=5),
        ),
    ]
