# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='Reviewed',
        ),
    ]
