# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaint', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='a', max_length=1)),
                ('Comment', models.CharField(blank=True, max_length=100, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.Complaint')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
