# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('ComplaintId', 'UserId')]),
        ),
    ]
