# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 05:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('HomeLocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('City', models.CharField(max_length=3)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=40)),
                ('FbId', models.CharField(blank=True, max_length=20, null=True)),
                ('Rating', models.FloatField(default=50)),
                ('Credit', models.FloatField(default=0)),
                ('DeActivate', models.BooleanField(default=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
